### ISSUE TITLE
question on getting started

### ISSUE THREAD

**Issue by furiel** [vodik/hytest#1]
@vodik I would like to try out this nice project, though I do not know how get started. Can you please explain, maybe add a little paragraph in the readme?

What I tried is to create a virtualenv, install hytest with setup.py, and then execute the provided test_example.hy through hy interpreter, but there was no output:

```
$ pwd
/tmp/hytest
$ virtualenv virtenv
New python executable in /tmp/hytest/virtenv/bin/python
Installing setuptools, pip, wheel...done.
$ source virtenv/bin/activate
(virtenv) $ git clone https://github.com/vodik/hytest
[...]
(virtenv) $ cd hytest/
(virtenv) $ python setup.py install
[...]
Finished processing dependencies for hytest==0.0.1
(virtenv) $ cd ..
(virtenv) $ ls
hytest  virtenv
(virtenv) $ cp hytest/tests/test_example.hy .
(virtenv) $ ls
hytest  test_example.hy  virtenv
(virtenv) $ export PYTHONPATH=hytest
(virtenv) $ hy test_example.hy 
(virtenv) $ 
```
and I expected to see printout about the failing testcase. How is this supposed to work?

**Comment by vodik** [comment]
Hey, thanks for the interest!

So as a preface, and hopefully not too disappointingly, I'm not so sure how much of a useful state this project is actually in. It was developed against an older version of Hy and a much older version of pytest. I haven't had a chance to get around to forward porting it. So YMMV

It was also a way for me to learn Hy, and thus very rough.

That said, this is a pytest plugin. It can't run tests on its own, you must use pytest. What it does is teaches pytest how to run tests written in Hy. Try instead of doing

```bash
$ hy test_example.hy
```

try:

```bash
$ pytest test_example.hy
```

Hy already internally uses pytest for its own testing - and writes lots of tests in Hy to test itself. So maybe a better way forward, it makes more sense to try to reuse that code than it does to try and reimplement it here.

I do have some extra functionality, like making `set_break` drop into a Hy repl, and might be able to improve the assert rewrite to make it more aware of Hy expression, and that certainly makes sense to maintain here.

**Comment by vodik** [comment]
Okay, so with https://github.com/hylang/hy/pull/1529 you shouldn't even need this project anymore, Hy itself will provide an adequate pytest plugin.

I may continue hacking on this to see if I can do something clever with macros for fixtures, or extend pytest to see how far I can push it.

**Comment by furiel** [comment]
Thank you for the explanation and the PR to hylang. It indeed works when calling through pytest (except `test-set-trace`, when I got `AttributeError: 'CaptureManager' object has no attribute 'suspendcapture'`, though the the other kind of tests are enough for me.

I think we can close this issue now and I continue to follow https://github.com/hylang/hy/pull/1529.

**Comment by vodik** [comment]
Yeah, I'm not surprised that doesn't work, the pytest APIs have changed there and I haven't had a chance to revisit this.

But hopefully you won't even need this package soon.
